from sc2_mcts import *
from enum import Enum

class Mcts:

    def __init__(self, state: State, seed: int, rollout_end_time: int, exploration: float, value_heuristic: ValueHeuristic, rollout_heuristic: RolloutHeuristic) -> Mcts: ...
    def update_root_state(self, state: State) -> None : ...
    def get_root_state(self) -> State: ...
    def get_root_node(self) -> Node: ...
    def to_string(self) -> str: ...
    def start_search(self) -> None: ...
    def stop_search(self) -> None: ...
    def get_best_action(self) -> Action: ...
    def perform_action(self, action:Action) -> None: ...
    def get_number_of_rollouts(self) -> int: ...

def state_builder(minerals: int,
                  vespene: int,
                  population: int,
                  incoming_population: int,
                  population_limit:int,
                  bases: list[Base],
                  constructions: list[Construction],
                  occupied_worker_timers: list[int],
                  end_time: int) -> State : ...

class State:
    def __init__(self): ...
    def perform_action(self, action: Action) -> None: ...
    def to_string(self) -> str: ...
    def get_minerals(self) -> int: ...
    def get_vespene(self) -> int: ...
    def get_incoming_population(self) -> int: ...
    def get_population(self) -> int: ...
    def get_occupied_population(self) -> int: ...
    def get_mineral_gained_per_timestep(self) -> int: ...
    def get_vespene_gained_per_timestep(self) -> int: ...
    def get_mineral_workers(self) -> int: ...
    def get_vespene_workers(self) -> int: ...

class Base:
    def __init__(self, id: int,  mineral_fields: int, vespene_geysers: int, vespene_collectors: int): ...
    def __init__(self): ...

class Construction:
    def __init__(self, time_left: int, action: Action): ...
    def get_time_left(self) -> int: ...

class Node:
    def to_string(self) -> str: ...
    def get_state(self) -> State: ...

class Action(Enum):
    none = 0
    build_worker = 1
    build_base = 2
    build_vespene_collector = 3
    build_house = 4

class ValueHeuristic(Enum):
     UCT = 0

class RolloutHeuristic(Enum):
    random = 0
    weighted_choice = 1



